---
ID: "a2f624d5-eff2-44f9-9172-33f9b58453ab"
Parent: "cf28bef5-045c-4b7f-81e8-ac82486633da"
Template: "3a45a723-64ee-4919-9d41-02fd40fd1466"
Path: /sitecore/layout/Layouts/Project/Blog/Default
DB: master
SharedFields:
- ID: "a036b2bc-ba04-44f6-a75f-bae6cd242abf"
  Hint: Path
  Value: ~/Views/Blog/Layout/Default.cshtml
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200316T134244Z
