---
ID: "ed4e6e9d-036b-407e-afb7-6bf5a35394dd"
Parent: "91fab4f6-3fb7-4103-bb85-dbded3cbc3cc"
Template: "267d9ac7-5d85-4e9d-af89-99ab296cc218"
Path: /sitecore/content/Shop/Shop Dictionary/Home/Products
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: apps/32x32/books.png
Languages:
- Language: "ru-RU"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200316T063631Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
