---
ID: "7d09401e-e491-4d39-8815-df03e603358f"
Parent: "32b2ebca-2d41-4df7-ba75-b8b8d67f0383"
Template: "32b2ebca-2d41-4df7-ba75-b8b8d67f0383"
Path: /sitecore/templates/Feature/ReusableComponents/Button Background Colors/Color/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200226T111140Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
