---
ID: "293a3451-b671-4fc0-a7b7-6d2469650487"
Parent: "e6880c59-434e-4480-8f97-a5903f0e53ca"
Template: "e6880c59-434e-4480-8f97-a5903f0e53ca"
Path: /sitecore/templates/Feature/ReusableComponents/Rendering Parameters/Hero Banner Rendering Parameters/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200226T120639Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
