---
ID: "65caed63-b69c-443e-878f-0643d90216c4"
Parent: "ed4e6e9d-036b-407e-afb7-6bf5a35394dd"
Template: "6d1cd897-1936-4a3a-a511-289a94c2a7b1"
Path: /sitecore/content/Shop/Shop Dictionary/Home/Products/Products is not find
DB: master
SharedFields:
- ID: "580c75a8-c01a-4580-83cb-987776ceb3af"
  Hint: Key
  Value: Products is not find
Languages:
- Language: "ru-RU"
  Fields:
  - ID: "2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e"
    Hint: Phrase
    Value: Продукты не найдены
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200316T064552Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
